- include: create_deploy_user.yml
- include: set_enviroment_variables.yml

- name: installing gem dependencies
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - libpq-dev
    - libssl-dev
    - postgresql-client
    - g++
    - git