- name: Remove apache2
  apt: name=apache2 state=absent

- name: Add key for passenger
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7

- name: Apt via https
  action: apt pkg={{ item }} state=installed
  with_items:
   - apt-transport-https
   - ca-certificates

- name: Apt add passenger to list
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main' state=present update_cache=yes

- name: Install nginx
  action: apt pkg={{ item }} state=installed
  with_items:
   - nginx-extras
   - passenger

- name: enable passenger in nginx.conf
  replace: dest=/etc/nginx/nginx.conf regexp='# include /etc/nginx/passenger.conf;' replace='include /etc/nginx/passenger.conf;'
  notify: nginx reload

- name: set passenger_max_pool_size to 3
  lineinfile: dest=/etc/nginx/passenger.conf regexp="passenger_max_pool_size" line="passenger_max_pool_size 3;"
  notify: nginx reload

- name: add passenger conf to ngnix sites-available
  template: src=etc/nginx/sites-available/_passenger_site.conf dest=/etc/nginx/sites-available/{{app_deploy_name}}.conf owner=root group=root mode=0644
  notify: nginx reload

- name: link _passenger_site.conf to ngnix sites-enabled
  file: src=/etc/nginx/sites-available/{{app_deploy_name}}.conf dest=/etc/nginx/sites-enabled/{{app_deploy_name}}.conf owner=root group=root state=link
  notify: nginx reload

- name: add redirect conf to ngnix sites-available
  template: src=etc/nginx/sites-available/_redirect.conf dest=/etc/nginx/sites-available/{{app_deploy_name}}_redirect.conf owner=root group=root mode=0644
  notify: nginx reload

- name: link _passenger_site.conf to ngnix sites-enabled
  file: src=/etc/nginx/sites-available/{{app_deploy_name}}_redirect.conf dest=/etc/nginx/sites-enabled/{{app_deploy_name}}_redirect.conf owner=root group=root state=link
  notify: nginx reload