- name: Remove ngnix
  apt: name={{item}} state=absent
  with_items:
   - ngnix
   - nginx-extras

- name: Remove nginx-extras
  apt: name=nginx-extras state=absent

- name: Add key for passenger
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7

- name: Apt via https
  action: apt pkg={{ item }} state=installed
  with_items:
   - apt-transport-https
   - ca-certificates

- name: Apt add passenger to list
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ansible_distribution_release}} main' state=present update_cache=yes

- name: Install apache2, passenger
  action: apt pkg={{ item }} state=installed
  with_items:
   - apache2
   - libapache2-mod-passenger

- name: enable the Passenger Apache module
  apache2_module: state=present name=passenger

- name: create pagespeed cache folder
  file: dest=/var/ngx_pagespeed_cache recurse=yes mode=0755 state=directory owner=www-data group=www-data

- stat: path=/etc/apache2/mods-available/pagespeed.conf
  register: pagespeed_conf_file

- name: Install mod-pagespeed
  apt: deb="https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb"
  notify: apache2 restart
  when: pagespeed_conf_file.stat.exists == False

- name: disable the pagespeed Apache modules until i can figure it out
  apache2_module: state=absent name={{item}}
  notify: apache2 restart
  with_items:
    - pagespeed

- name: enable the Apache modules
  apache2_module: state=present name={{item}}
  notify: apache2 restart
  with_items:
    - headers
    - expires
    - passenger

- name: add passenger conf to apache2 conf-available
  copy: src=etc/apache2/conf-available/passenger.conf dest=/etc/apache2/conf-available/passenger.conf owner=root group=root mode=0644
  notify: apache2 restart

- name: link passenger.conf to apache2 conf-enabled
  file: src=/etc/apache2/conf-available/passenger.conf dest=/etc/apache2/conf-enabled/passenger.conf owner=root group=root state=link
  notify: apache2 restart

- name: add site conf to apache2 sites-available
  template: src=etc/apache2/sites-available/_passenger_site.conf dest=/etc/apache2/sites-available/{{app_deploy_name}}.conf owner=root group=root mode=0644
  notify: apache2 restart

- name: link site.conf to ngnix sites-enabled
  file: src=/etc/apache2/sites-available/{{app_deploy_name}}.conf dest=/etc/apache2/sites-enabled/{{app_deploy_name}}.conf owner=root group=root state=link
  notify: apache2 restart