- include: placeholder_app.yml
- include: install_service.yml
- include: set_deploy_access.yml

- name: installing gem dependencies
  apt: name={{item}} state=present
  with_items:
    - build-essential
    - libpq-dev
    - libssl-dev
    - postgresql-client
    - g++
    - git

