- name: set RAILS_ENV in .bashrc
  lineinfile: dest=/home/{{app_deploy_name}}/.bashrc insertafter="^# for examples" regexp="RAILS_ENV=" line="export RAILS_ENV=production.yml"

- name: set app enviroment variables
  lineinfile: dest=/home/my_grocery_price_book_www/.bashrc insertafter="^# for examples" regexp="{{ item.key }}=" line="export {{ item.key }}={{ item.value }}"
  with_dict: "{{app_env}}"
