- name: create development pg ubuntu user
  postgresql_user: name=ubuntu role_attr_flags=CREATEDB,SUPERUSER
  become: yes
  become_user: postgres

- name: create development on database
  postgresql_db: name=development encoding='UTF-8'
  become: yes
  become_user: postgres

- name: create test on database
  postgresql_db: name=test encoding='UTF-8'
  become: yes
  become_user: postgres