---
- hosts: all
  remote_user: root
  roles:
    - common
    - azavea.swapfile
    - laggyluke.newrelic-sysmond
    - loggly

- hosts: production-db
  remote_user: root
  roles:
    - postgresql

- hosts: production-apps
  remote_user: root
  roles:
    - app-runner

- hosts: production-web
  remote_user: root
  roles:
    - web-runner