- name: add user gems path to .bashrc
  lineinfile: dest=/home/ubuntu/.bashrc line="PATH=\"$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH\""

- name: Install bundler
  gem: name={{item}} state=latest user_install=yes
  sudo: no
  with_items:
    - bundler
