- name: ensure github.com is a known host
  become: no
  known_hosts:
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    host: "github.com"

- include: gem_tools.yml
- include: node_tools.yml
- include: mailcatcher.yml

- name: installing phantomjs dependencies
  apt: name={{item}} state=present
  with_items:
    - libfontconfig

- name: bundle install
  bundler: state=present gemfile=/vagrant/Gemfile executable=~/.gem/ruby/2.3.0/bin/bundle
  become: no

- name: load database.yml
  template: src=vagrant/config/database.yml dest=/vagrant/config/database.yml
  become: no

- name: database setup
  shell: /bin/bash -l -c "bin/setup > ~/bin_setup.txt"
  become: no
  args:
    chdir: /vagrant
    creates: ~/bin_setup.txt
