- name: installing nodejs
  apt: name={{item}} state=present
  with_items:
    - nodejs
    - npm
    - nodejs-legacy

- name: Install "eslint" node.js package globally.
  npm: name={{item}} global=yes # for pronto-eslint
  with_items:
    - eslint
    - eslint-config-standard
    - eslint-plugin-standard
    - eslint-plugin-react
